
public enum TokenType {

    //single tokens
    COLON, PERIOD, COMMA, PLUS, MINUS, MULTIPLY, DIVIDE,
    LEFT_SQR_BRACE, RIGHT_SQR_BRACE, LEFT_PAREN, RIGHT_PAREN, DOUBLE_QUOTE,


    //one or two char tokens
    EQUALITY, GREATER,
    LESS, GREATER_EQUAL,
    LESS_EQUAL, NOTEQUAL,


    //KEYWORDS
    OUTPUT, ON, CREATE, CONSTANT, ELSE_IF, ME, UNTIL, PUBLIC, PRIVATE, ALERT, DETECT, ALWAYS,
    CHECK, PARENT, BLUEPRINT, NATIVE, INHERITS, CAST, INPUT, SAY, NOW, WHILE, PACKAGE, TIMES, REPEAT,
    ELSE, RETURNS, RETURN, AND, OR, NULL, STATIC, ACTION, INTEGER_KEYWORD, NUMBER_KEYWORD, TEXT, BOOLEAN_KEYWORD,
    USE, NOT, IF, END, CLASS, EOF, MODULO,

    //LITERALS
    BOOLEAN, INT, DECIMAL, ID, STRING,

    //Whitespace and comments
     WS, COMMENTS
}
